version: "3"

services:
  spotdl-gui:
    image: lffpicard/spotdl-gui:latest
    container_name: spotDL-GUI
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /path/to/your/music:/music       # change this to your music folder
      - /path/to/appdata/spotDL-GUI:/config  # change this to your config folder
    environment:
      - PUID=1000
      - PGID=1000
